# Generated by Django 4.2.30 on 2026-04-20 14:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('active_trucks', models.IntegerField(default=0)),
                ('on_time_rate', models.FloatField(default=0)),
                ('avg_speed', models.FloatField(default=0)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('critical_alerts', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kpi_metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=20, unique=True)),
                ('driver', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('moving', 'Moving'), ('delayed', 'Delayed'), ('stopped', 'Stopped'), ('delivered', 'Delivered'), ('maintenance', 'Maintenance')], default='moving', max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('speed', models.IntegerField(default=0)),
                ('eta', models.CharField(max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('cargo', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=20)),
                ('coordinates', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trucks',
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('status', models.CharField(choices=[('done', 'Done'), ('active', 'Active'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='api.truck')),
            ],
            options={
                'db_table': 'checkpoints',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cargo_type', models.CharField(choices=[('electronics', 'Electronics'), ('fmcg', 'FMCG'), ('agri', 'Agriculture'), ('pharma', 'Pharmaceuticals'), ('fuel', 'Fuel Tanks')], max_length=20)),
                ('weight', models.FloatField()),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('truck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_info', to='api.truck')),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info'), ('success', 'Success')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.truck')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-timestamp'],
            },
        ),
    ]
