# Generated by Django 6.0.4 on 2026-05-18 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleetdriver',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='fleetdriver',
            name='current_speed',
        ),
        migrations.RemoveField(
            model_name='fleetdriver',
            name='deliveries_count',
        ),
        migrations.RemoveField(
            model_name='fleetdriver',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='fleetdriver',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='fleetdriver',
            name='last_active_at',
        ),
        migrations.RemoveField(
            model_name='fleetdriver',
            name='last_location_update',
        ),
        migrations.RemoveField(
            model_name='fleetdriver',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='fleetdriver',
            name='license_state',
        ),
        migrations.RemoveField(
            model_name='fleetdriver',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='fleetdriver',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='fleetdriver',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='fleetmission',
            name='created_by_admin_id',
        ),
        migrations.RemoveField(
            model_name='fleetmission',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='fleetmission',
            name='distance_remaining_m',
        ),
        migrations.RemoveField(
            model_name='fleetmission',
            name='eta',
        ),
        migrations.RemoveField(
            model_name='fleetmission',
            name='route_polyline',
        ),
        migrations.RemoveField(
            model_name='fleetmission',
            name='speed_kmh',
        ),
        migrations.RemoveField(
            model_name='fleetmission',
            name='stops',
        ),
        migrations.RemoveField(
            model_name='fleettruck',
            name='is_moving',
        ),
        migrations.RemoveField(
            model_name='fleettruck',
            name='kilometers_travelled_km',
        ),
        migrations.RemoveField(
            model_name='fleettruck',
            name='make',
        ),
        migrations.RemoveField(
            model_name='fleettruck',
            name='model',
        ),
        migrations.RemoveField(
            model_name='fleettruck',
            name='year',
        ),
        migrations.AlterField(
            model_name='fleetactivity',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='api.fleetdriver'),
        ),
        migrations.AlterField(
            model_name='fleetactivity',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='api.fleetmission'),
        ),
        migrations.AlterField(
            model_name='fleetactivity',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='api.fleettruck'),
        ),
        migrations.AlterField(
            model_name='fleetdriver',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='api.fleettruck'),
        ),
        migrations.AlterField(
            model_name='fleetdriverperformancedaily',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_performance', to='api.fleetdriver'),
        ),
        migrations.AlterField(
            model_name='fleetmission',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='api.fleetdriver'),
        ),
        migrations.AlterField(
            model_name='fleetmission',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='api.fleettruck'),
        ),
        migrations.AlterField(
            model_name='trucklocation',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_history', to='api.fleetdriver'),
        ),
        migrations.AlterField(
            model_name='trucklocation',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='api.fleettruck'),
        ),
    ]
