# Generated by Django 6.0.4 on 2026-05-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fleetadminauditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetmission',
            name='avg_speed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='fleetmission',
            name='compressed_trail',
            field=models.JSONField(blank=True, default=list, help_text='Compressed list of [lat, lng, ts] for auditing'),
        ),
        migrations.AddField(
            model_name='fleetmission',
            name='max_speed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
    ]
