# Generated by Django 4.2.30 on 2026-04-28 08:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_truck_auto_routing_enabled_truck_current_route_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(default=0)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recorded_at', models.DateTimeField()),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_points', to='api.route')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_points', to='api.truck')),
            ],
            options={
                'db_table': 'track_points',
                'ordering': ['recorded_at'],
                'indexes': [models.Index(fields=['truck', 'recorded_at'], name='track_point_truck_i_206c07_idx'), models.Index(fields=['route', 'recorded_at'], name='track_point_route_i_4ebd86_idx')],
            },
        ),
    ]
