# Generated by Django 4.2.30 on 2026-04-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_route_fields'),
        ('api', '0006_add_ml_models'),
    ]

    operations = [
    ]
