# Generated by Django 6.0.4 on 2026-05-05 11:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_fuel_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetAdminAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('admin_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.UUIDField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'fleet_admin_audit_logs',
            },
        ),
        migrations.CreateModel(
            name='FleetDriver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fleet_id', models.UUIDField(db_index=True)),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('license_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('license_state', models.CharField(blank=True, max_length=10, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('on_leave', 'On Leave')], db_index=True, default='active', max_length=20)),
                ('on_duty', models.BooleanField(db_index=True, default=False)),
                ('performance_mark', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deliveries_count', models.IntegerField(default=0)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('achievements', models.JSONField(blank=True, default=dict)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fleet_drivers',
            },
        ),
        migrations.CreateModel(
            name='FleetDriverPerformanceDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('deliveries_count', models.IntegerField(default=0)),
                ('on_time_count', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('harsh_braking_count', models.IntegerField(default=0)),
                ('idling_minutes', models.IntegerField(default=0)),
                ('fuel_efficiency_liters_per_100km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('safety_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('efficiency_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fleet_driver_performance_daily',
            },
        ),
        migrations.CreateModel(
            name='FleetMission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fleet_id', models.UUIDField(db_index=True)),
                ('mission_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('assigned', 'Assigned'), ('enroute', 'En Route'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('origin', models.JSONField()),
                ('destination', models.JSONField()),
                ('current_location', models.JSONField(blank=True, null=True)),
                ('route_polyline', models.TextField(blank=True, null=True)),
                ('distance_total_m', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('distance_remaining_m', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('progress_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('cargo', models.JSONField(blank=True, default=dict)),
                ('stops', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_admin_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fleet_missions',
            },
        ),
        migrations.CreateModel(
            name='FleetMissionDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispute_type', models.CharField(choices=[('incorrect_location', 'Incorrect Location'), ('wrong_cargo', 'Wrong Cargo'), ('timeout', 'Timeout'), ('customer_issue', 'Customer Issue'), ('safety_concern', 'Safety Concern'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by_admin_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fleet_mission_disputes',
            },
        ),
        migrations.CreateModel(
            name='FleetMissionEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('status_changed', 'Status Changed'), ('location_updated', 'Location Updated'), ('stop_completed', 'Stop Completed'), ('driver_assigned', 'Driver Assigned'), ('truck_assigned', 'Truck Assigned'), ('paused', 'Mission Paused'), ('resumed', 'Mission Resumed'), ('dispute_filed', 'Dispute Filed')], max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('trace_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'fleet_mission_events',
            },
        ),
        migrations.CreateModel(
            name='FleetMissionStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stop_order', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fleet_mission_stops',
            },
        ),
        migrations.CreateModel(
            name='FleetTruck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fleet_id', models.UUIDField(db_index=True)),
                ('truck_identifier', models.CharField(db_index=True, max_length=100, unique=True)),
                ('plate', models.CharField(db_index=True, max_length=20, unique=True)),
                ('vin', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('telematics_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('fuel_capacity_liters', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('fuel_consumed_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('odometer_km', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('kilometers_travelled_km', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('enroute', 'En Route'), ('maintenance', 'Maintenance'), ('decommissioned', 'Decommissioned')], db_index=True, default='idle', max_length=20)),
                ('is_moving', models.BooleanField(default=False)),
                ('last_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_ts', models.DateTimeField(blank=True, null=True)),
                ('maintenance_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'fleet_trucks',
            },
        ),
        migrations.RenameIndex(
            model_name='fuelconsumption',
            new_name='fuel_consum_truck_i_b4faf2_idx',
            old_name='fuel_consumption_truck_id_start_idx',
        ),
        migrations.RenameIndex(
            model_name='fuelconsumption',
            new_name='fuel_consum_route_i_9eb0dd_idx',
            old_name='fuel_consumption_route_id_start_idx',
        ),
        migrations.RenameIndex(
            model_name='fuelrefuel',
            new_name='fuel_refuel_truck_i_d67500_idx',
            old_name='fuel_refuel_truck_id_refuel_d_idx',
        ),
        migrations.RenameIndex(
            model_name='location',
            new_name='locations_name_ce8723_idx',
            old_name='locations_name_idx',
        ),
        migrations.RenameIndex(
            model_name='location',
            new_name='locations_locatio_f7b031_idx',
            old_name='locations_type_idx',
        ),
        migrations.AlterField(
            model_name='route',
            name='geometry',
            field=models.JSONField(blank=True, default=dict, help_text='GeoJSON LineString geometry from OSRM routing service', null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='route_color',
            field=models.CharField(default='#3b82f6', help_text='Hex color for route visualization (deterministic per truck)', max_length=7),
        ),
        migrations.AlterField(
            model_name='truck',
            name='route_geojson',
            field=models.JSONField(blank=True, default=dict, help_text='GeoJSON LineString geometry for persistent route display', null=True),
        ),
        migrations.AddIndex(
            model_name='fleetadminauditlog',
            index=models.Index(fields=['-created_at'], name='fleet_audit_created_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetadminauditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='fleet_audit_resource_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetdriver',
            index=models.Index(fields=['fleet_id', 'status'], name='fleet_drv_fleet_st_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetdriver',
            index=models.Index(fields=['on_duty', 'status'], name='fleet_drv_on_duty_st_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetdriver',
            index=models.Index(fields=['-performance_mark'], name='fleet_drv_perf_idx'),
        ),
        migrations.AddField(
            model_name='fleetdriverperformancedaily',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fleetdriver'),
        ),
        migrations.AddField(
            model_name='fleetmission',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fleetdriver'),
        ),
        migrations.AddField(
            model_name='fleetmissiondispute',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fleetdriver'),
        ),
        migrations.AddField(
            model_name='fleetmissiondispute',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fleetmission'),
        ),
        migrations.AddField(
            model_name='fleetmissionevent',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fleetdriver'),
        ),
        migrations.AddField(
            model_name='fleetmissionevent',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fleetmission'),
        ),
        migrations.AddField(
            model_name='fleetmissionstop',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops_detail', to='api.fleetmission'),
        ),
        migrations.AddField(
            model_name='fleetmissiondispute',
            name='stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fleetmissionstop'),
        ),
        migrations.AddField(
            model_name='fleettruck',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fleetdriver'),
        ),
        migrations.AddField(
            model_name='fleetmissionevent',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fleettruck'),
        ),
        migrations.AddField(
            model_name='fleetmission',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fleettruck'),
        ),
        migrations.AddIndex(
            model_name='fleetdriverperformancedaily',
            index=models.Index(fields=['driver', '-date'], name='fleet_daily_drv_dt_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fleetdriverperformancedaily',
            unique_together={('driver', 'date')},
        ),
        migrations.AddIndex(
            model_name='fleetmissionstop',
            index=models.Index(fields=['mission', 'stop_order'], name='fleet_stop_mission_order_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetmissionstop',
            index=models.Index(fields=['status'], name='fleet_stop_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fleetmissionstop',
            unique_together={('mission', 'stop_order')},
        ),
        migrations.AddIndex(
            model_name='fleetmissiondispute',
            index=models.Index(fields=['mission', 'status'], name='fleet_disp_mis_st_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetmissiondispute',
            index=models.Index(fields=['driver', 'status'], name='fleet_disp_drv_st_idx'),
        ),
        migrations.AddIndex(
            model_name='fleettruck',
            index=models.Index(fields=['fleet_id', 'status'], name='fleet_trk_fleet_st_idx'),
        ),
        migrations.AddIndex(
            model_name='fleettruck',
            index=models.Index(fields=['plate'], name='fleet_truck_plate_idx'),
        ),
        migrations.AddIndex(
            model_name='fleettruck',
            index=models.Index(fields=['-updated_at'], name='fleet_truck_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetmissionevent',
            index=models.Index(fields=['-created_at'], name='fleet_event_created_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetmissionevent',
            index=models.Index(fields=['event_type', '-created_at'], name='fleet_event_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetmission',
            index=models.Index(fields=['fleet_id', 'status'], name='fleet_mis_fleet_st_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetmission',
            index=models.Index(fields=['truck_id', 'status'], name='fleet_mis_truck_st_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetmission',
            index=models.Index(fields=['driver_id', 'status'], name='fleet_mis_drv_st_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetmission',
            index=models.Index(fields=['-created_at'], name='fleet_mis_cr_idx'),
        ),
    ]
