# Generated by Django 6.0.4 on 2026-05-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_v2_fleet_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetmission',
            name='mission_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
