# Generated by Django 6.0.4 on 2026-05-06 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_fleetmission_mission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetdriver',
            name='performance_mark',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
