# Generated by Django 6.0.4 on 2026-05-08 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_delivery_tracking'),
        ('api', '0013_add_mobile_tracking_models'),
    ]

    operations = [
    ]
