# Generated by Django 6.0.4 on 2026-05-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20260508_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucklocation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
