# Generated by Django 6.0.4 on 2026-05-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_trucklocation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleettruck',
            name='current_location',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='fleettruck',
            name='speed_kmh',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
