# Generated by Django 6.0.4 on 2026-05-17 08:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_fleet_activity_raw_sql'),
    ]

    operations = [
        # FleetActivity table already created by raw SQL in 0017_fleet_activity_raw_sql
        # Skip CreateModel operation to avoid "table already exists" error
        migrations.RemoveField(
            model_name='alert',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='currentlocation',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='fuelalert',
            name='truck',
        ),
        migrations.RemoveIndex(
            model_name='fuelconsumption',
            name='fuel_consum_truck_i_b4faf2_idx',
        ),
        migrations.RemoveIndex(
            model_name='fuelconsumption',
            name='fuel_consum_route_i_9eb0dd_idx',
        ),
        migrations.RemoveIndex(
            model_name='fuelrefuel',
            name='fuel_refuel_truck_i_d67500_idx',
        ),
        migrations.DeleteModel(
            name='KPI',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='locations_name_ce8723_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='locations_locatio_f7b031_idx',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='destination_location',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='origin_location',
        ),
        migrations.RemoveField(
            model_name='route',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='routeoptimization',
            name='route',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='current_route',
        ),
        migrations.RemoveField(
            model_name='routeoptimization',
            name='truck',
        ),
        migrations.RemoveIndex(
            model_name='trackpoint',
            name='track_point_truck_i_206c07_idx',
        ),
        migrations.RemoveIndex(
            model_name='trackpoint',
            name='track_point_route_i_4ebd86_idx',
        ),
        migrations.RemoveField(
            model_name='truckfuel',
            name='truck',
        ),
        # Skip AddField for fleetactivity - table created by raw SQL in 0017
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Checkpoint',
        ),
        migrations.DeleteModel(
            name='CurrentLocation',
        ),
        migrations.DeleteModel(
            name='FuelAlert',
        ),
        migrations.RemoveField(
            model_name='fuelconsumption',
            name='route',
        ),
        migrations.RemoveField(
            model_name='fuelconsumption',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='fuelrefuel',
            name='truck',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='RouteOptimization',
        ),
        migrations.RemoveField(
            model_name='trackpoint',
            name='route',
        ),
        migrations.RemoveField(
            model_name='trackpoint',
            name='truck',
        ),
        migrations.DeleteModel(
            name='TruckFuel',
        ),
        # Skip AddIndex for fleetactivity - table created by raw SQL in 0017
        migrations.DeleteModel(
            name='FuelConsumption',
        ),
        migrations.DeleteModel(
            name='FuelRefuel',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='TrackPoint',
        ),
        migrations.DeleteModel(
            name='Truck',
        ),
    ]
