# Generated by Django 6.0.4 on 2026-05-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_fleetactivity_remove_alert_truck_remove_cargo_truck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetdriver',
            name='fleet_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fleettruck',
            name='fleet_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
