# Generated by Django 6.0.4 on 2026-05-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_fleetdriver_fleet_id_alter_fleettruck_fleet_id'),
    ]

    operations = [
        # FleetActivity model already exists from migrations 0017 and 0018
        # This migration marks the model as complete without re-creating the table
        migrations.RunSQL(
            sql="SELECT 1;",  # No-op SQL statement
            reverse_sql="SELECT 1;",
        ),
    ]
