# Generated by Django 4.2.30 on 2026-04-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='truck',
            name='distance_travelled',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='truck',
            name='total_distance',
            field=models.FloatField(default=1000.0),
        ),
    ]
