# Generated by Django 4.2.30 on 2026-04-27 04:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alert_driver_name_truck_distance_travelled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('origin_coordinates', models.JSONField(default=dict)),
                ('destination_coordinates', models.JSONField(default=dict)),
                ('waypoints', models.JSONField(default=list)),
                ('distance_km', models.FloatField(default=0)),
                ('estimated_duration_hours', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('optimized', 'Optimized')], default='planned', max_length=20)),
                ('suggested_speeds', models.JSONField(default=dict)),
                ('optimization_score', models.FloatField(default=0)),
                ('traffic_prediction', models.JSONField(default=dict)),
                ('weather_factors', models.JSONField(default=dict)),
                ('current_waypoint_index', models.IntegerField(default=0)),
                ('distance_travelled_km', models.FloatField(default=0)),
                ('time_elapsed_hours', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='api.truck')),
            ],
            options={
                'db_table': 'routes',
                'ordering': ['-created_at'],
            },
        ),
    ]
