# Generated by Django 4.2.30 on 2026-04-27 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='auto_routing_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='current_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truck_active', to='api.route'),
        ),
        migrations.AddField(
            model_name='truck',
            name='destination',
            field=models.CharField(default='Bulawayo', max_length=100),
        ),
        migrations.AddField(
            model_name='truck',
            name='destination_coordinates',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='origin',
            field=models.CharField(default='Harare', max_length=100),
        ),
        migrations.AddField(
            model_name='truck',
            name='origin_coordinates',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
