"""
Django settings for Logistics project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import sys
import dj_database_url

# Debug: Print when settings are being loaded
print(f"[SETTINGS] Loading Logistics.settings", file=sys.stderr)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print(f"[SETTINGS] BASE_DIR: {BASE_DIR}", file=sys.stderr)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-jog5cd&da78_mp8ugp*z6acd6*p14bygdcn_$-8gm*1&ln@2zq')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Allow Railway, Render, Vercel frontend, localhost, and development hosts
ALLOWED_HOSTS = [
    'pulsetrack-back.onrender.com',
    'pulsetrack-frontend-henna.vercel.app',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'server.api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Must be at the top
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # <--- ADD THIS LINE
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Logistics.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Logistics.wsgi.application'


# Database - PostgreSQL on Railway, SQLite for local development
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# ============================================================
# DATABASE CONFIGURATION (Hardcoded for Render)
# ============================================================
print(f"[SETTINGS] Configuring database...", file=sys.stderr)

# Your specific PostgreSQL URL
DATABASE_URL_HARDCODED = 'postgresql://pulse_track_backend_db_l723_user:2lTJw1fEiU2NQrYA7YOFknY4mHikUH4p@dpg-d84r01btqb8s73fj9dl0-a/pulse_track_backend_db_l723'

try:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL_HARDCODED,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
    print(f"[SETTINGS] ✓ Database linked successfully via hardcoded URL", file=sys.stderr)
except Exception as e:
    print(f"[SETTINGS] ✗ ERROR: Failed to connect to PostgreSQL: {e}", file=sys.stderr)
    # Fallback to SQLite ONLY if the hardcoded URL fails
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# MongoDB configuration (for future integration)
# MONGODB_CONFIG = {
#     'host': config('MONGO_HOST', default='localhost'),
#     'port': config('MONGO_PORT', default=27017, cast=int),
#     'db': config('MONGO_DB', default='fleet_management'),
#     'username': config('MONGO_USER', default=None),
#     'password': config('MONGO_PASSWORD', default=None),
# }

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# CORS Configuration - Support cross-network communication
# Development: Allow all origins for flexibility during development
# Production: Should be restricted to known origins
if DEBUG:
    # Development: Allow localhost and common Vite dev ports
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:5173',
        'http://localhost:5174',
        'http://localhost:5175',
        'http://localhost:5176',
        'http://localhost:5177',
        'http://localhost:5178',
        'http://127.0.0.1:5173',
        'http://127.0.0.1:5174',
        'http://127.0.0.1:5175',
        'http://127.0.0.1:5176',
        'http://127.0.0.1:5177',
        'http://127.0.0.1:5178',
        # For mobile app and other clients on same LAN
        'http://192.168.0.0:5173',  # Common router prefix
        'http://10.0.0.0:5173',      # Another common prefix
        'http://192.168.1.87:8081',
    ]
    # Also allow all origins in development for flexibility
    CORS_ALLOW_ALL_ORIGINS = True
else:
    # Production: Allow only Vercel frontend and Render backend
    CORS_ALLOWED_ORIGINS = [
        'https://pulsetrack-frontend-henna.vercel.app',
        'https://pulsetrack-back.onrender.com',
    ]
    CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOW_CREDENTIALS = True

# Additional CORS headers allowed
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Expose additional headers to client
CORS_EXPOSE_HEADERS = [
    'content-type',
    'x-csrftoken',
]

# CSRF Configuration - Trust frontend domains for cross-origin requests
# CSRF trusted origins for web frontend and mobile app cross-network communication
CSRF_TRUSTED_ORIGINS = [
    # Render backend domains
    'https://pulsetrack-back.onrender.com',
    'https://*.render.com',
    # Web frontend
    'https://pulsetrack-frontend-henna.vercel.app',
    'https://*.vercel.app',
    # Local development (web frontend ports)
    'http://localhost:5173',
    'http://localhost:5174',
    'http://localhost:5175',
    'http://localhost:5176',
    'http://localhost:5177',
    'http://localhost:5178',
    'http://127.0.0.1:5173',
    'http://127.0.0.1:5174',
    'http://127.0.0.1:5175',
    'http://127.0.0.1:5176',
    'http://127.0.0.1:5177',
    'http://127.0.0.1:5178',
    'http://192.168.1.236:5173',
    'http://192.168.0.0:5173',
    # Mobile app cross-network communication
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://192.168.1.236:8000',
    'http://10.0.2.2:8000',
    'https://pulsetrack-back.onrender.com:8000',
    'http://192.168.1.87:8081',
]

# CSRF Cookie Settings - Allow frontend to read and send CSRF token
CSRF_COOKIE_SECURE = not DEBUG  # Only secure in production
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token (necessary for SPAs)
CSRF_COOKIE_SAMESITE = 'Lax' if DEBUG else 'Lax'  # Lax allows safe cross-site requests
CSRF_COOKIE_AGE = 31449600  # One year
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

